### ISSUE TITLE
Wrong branch name in notification for pull requests

### ISSUE THREAD

**Issue by rochdev** [drone-plugins/drone-slack#62] opened 2017-09-20 13:39 UTC
When sending a notification for a pull request, the branch is displayed as being `master` instead of the name of the pull request.

For example I see: `*success* org/repo#abcd1234 (master) by user`

Instead of `master` I would expect to see something like `pr-123` or `pull/123`

**Comment by tboerger** [comment] 2017-09-20 15:14
This is an expected behavior as `branch` references the target branch and not where it comes from. I think `ref` is what you want to have.

**Comment by gtaylor** [comment] 2017-09-20 15:24
I don't recall this being the case with the 0.4 version of this plugin. This very behavior bit and confused us as well.

**Comment by bradrydzewski** [comment] 2017-09-20 15:54
drone tracks the __target__ branch for pull requests. There is a proposal to track both the source and target pull requests within drone core. https://github.com/drone/drone/issues/2222

I am going to close this because this is really a matter for drone core. The plugin uses the data it gets from drone server, so there is really nothing the plugin can do about it.

**Closed by bradrydzewski** 2017-09-20 15:54 UTC
