### ISSUE TITLE
How use plugin?

### ISSUE THREAD

**Issue by dhalturin** [drone-plugins/drone-slack#37] opened 2016-12-28 22:17 UTC
Hi.

If use plugin from pipeline:
```
pipeline:
  slack:
    image: plugins/slack
    webhook: url
    channel: dev
```

Build failed:
```
panic: runtime error: slice bounds out of range [recovered]
0s
2
	panic: runtime error: slice bounds out of range
0s
4
goroutine 1 [running]:
0s
5
panic(0x821140, 0xc82000a060)
0s
6
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
0s
7
github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli.HandleAction.func1(0xc8200e9468)
0s
8
	/go/src/github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli/app.go:476 +0x417
0s
9
panic(0x821140, 0xc82000a060)
0s
10
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
0s
11
main.message(0xc8200ea130, 0x9, 0xc8200ea150, 0xd, 0xc8200ea0e8, 0x6, 0xc8200ea17b, 0x3, 0x67, 0x0, ...)
0s
12
	/go/src/github.com/drone-plugins/drone-slack/plugin.go:92 +0x407
0s
13
main.Plugin.Exec(0xc8200ea130, 0x9, 0xc8200ea150, 0xd, 0xc8200ea0e8, 0x6, 0xc8200ea17b, 0x3, 0x67, 0x0, ...)
0s
14
	/go/src/github.com/drone-plugins/drone-slack/plugin.go:55 +0x7d
0s
15
main.run(0xc8200dcf00, 0x0, 0x0)
0s
16
	/go/src/github.com/drone-plugins/drone-slack/main.go:184 +0x91f
0s
17
reflect.Value.call(0x77f780, 0x96f8c8, 0x13, 0x8a8378, 0x4, 0xc8200e93c8, 0x1, 0x1, 0x0, 0x0, ...)
0s
18
	/usr/local/go/src/reflect/value.go:435 +0x120d
0s
19
reflect.Value.Call(0x77f780, 0x96f8c8, 0x13, 0xc8200e93c8, 0x1, 0x1, 0x0, 0x0, 0x0)
0s
20
	/usr/local/go/src/reflect/value.go:303 +0xb1
0s
21
github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli.HandleAction(0x77f780, 0x96f8c8, 0xc8200dcf00, 0x0, 0x0)
0s
22
	/go/src/github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli/app.go:485 +0x2ee
0s
23
github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli.(*App).Run(0xc820001080, 0xc82000a210, 0x1, 0x1, 0x0, 0x0)
0s
24
	/go/src/github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli/app.go:244 +0xb05
0s
25
main.main()
0s
26
	/go/src/github.com/drone-plugins/drone-slack/main.go:141 +0x1707
```

Need run docker container (docker run -d blablabla drone-slack) with env SLACK_WEBHOOK and use plugin from notify?

**Comment by bradrydzewski** [comment] 2016-12-29 14:18
duplicate of #28

**Closed by bradrydzewski** 2016-12-29 14:18 UTC
